INSERT INTO Feature (Name) VALUES ('Cheap');
INSERT INTO Feature (Name) VALUES ('Chinese Food');
INSERT INTO Feature (Name) VALUES ('Night Life');
INSERT INTO Feature (Name) VALUES ('Pet-friendly');
INSERT INTO Feature (Name) VALUES ('Brunch');
INSERT INTO Feature (Name) VALUES ('Asian Fusion');
INSERT INTO Feature (Name) VALUES ('American Food');
INSERT INTO Feature (Name) VALUES ('Family');
INSERT INTO Feature (Name) VALUES ('Exotic Food');
INSERT INTO Feature (Name) VALUES ('French');